apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: zedidtt0n-nodejs 
  janus-idp.io/tekton: zedidtt0n-nodejs
  backstage.io/kubernetes-id: zedidtt0n-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: zedidtt0n-nodejs
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  