apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: zedidtt0n-nodejs-gitops-repository
spec:
  url: https://github.com/rhtap-test-organization-jk/zedidtt0n-nodejs-gitops